### ISSUE TITLE
Is this extension available in the public marketplace?

### ISSUE THREAD

**Issue by poltj18** [flamencist/GenericConnectionViewer#2]
Great extension! 👍 I'm interested to know if you have plans to release it to the [public extensions marketplace](https://marketplace.visualstudio.com/search?target=AzureDevOps&category=Azure%20Pipelines&sortBy=Installs) so it can be installed in any Azure DevOps organization.

**Comment by flamencist** [comment]
Yes I would like to publish to the gallery. But I need to investigate a publish procedure

**Comment by flamencist** [comment]
I published https://marketplace.visualstudio.com/items?itemName=achermyanin.credentials-viewer. Please check. If all is ok please star project and close issue.

**Comment by poltj18** [comment]
Awesome! Thanks!
